version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homeapp
      - NODE_ENV=production
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homeapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: