version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/homeapp
      - NODE_ENV=development
    depends_on:
      - db
    command: sh -c "npm install && npm install recharts react-colorful && npm run dev"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homeapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_node_modules: